version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: 'Europe/Moscow'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps)'
      include: scope
    labels:
      - dependencies
    groups:
      dev-lint:
        patterns:
          - 'typescript'
          - 'prettier'
          - 'eslint*'
          - '@types/*'
        update-types:
          - minor
          - patch
      dev-tools:
        patterns:
          - 'vite'
          - 'esbuild'
          - 'serve'
          - 'concurrently'
          - 'html-minifier-terser'
          - 'lint-staged'
          - 'husky'
          - 'rimraf'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: 'Europe/Moscow'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(ci)'
      include: scope
    labels:
      - ci
    groups:
      actions-minor:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
